// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunVYwlxf7Lyq5d4B10tmOoUxBRrt4QL4',
    appId: '1:27828272558:web:22017a4a09ff564226dc3f',
    messagingSenderId: '27828272558',
    projectId: 'brokrapp-382604',
    authDomain: 'brokrapp-382604.firebaseapp.com',
    databaseURL: 'https://brokrapp-382604-default-rtdb.firebaseio.com',
    storageBucket: 'brokrapp-382604.firebasestorage.app',
    measurementId: 'G-RXJC47EGYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ4C5ZUTPvjChOozr5fvCHIasbkcp9EdA',
    appId: '1:27828272558:android:808a11fe43d835a426dc3f',
    messagingSenderId: '27828272558',
    projectId: 'brokrapp-382604',
    databaseURL: 'https://brokrapp-382604-default-rtdb.firebaseio.com',
    storageBucket: 'brokrapp-382604.firebasestorage.app',
  );
}
